/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ss_CONSTANTS_H
#define ss_CONSTANTS_H

#include "ss_types.h"



class ssConstants {
 public:
  ssConstants();

};

extern const ssConstants g_ss_constants;



#endif
