/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ss.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ss.pb-c.h"
void   rpc_request__init
                     (RpcRequest         *message)
{
  static RpcRequest init_value = RPC_REQUEST__INIT;
  *message = init_value;
}
size_t rpc_request__get_packed_size
                     (const RpcRequest *message)
{
  assert(message->base.descriptor == &rpc_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_request__pack
                     (const RpcRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_request__pack_to_buffer
                     (const RpcRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcRequest *
       rpc_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcRequest *)
     protobuf_c_message_unpack (&rpc_request__descriptor,
                                allocator, len, data);
}
void   rpc_request__free_unpacked
                     (RpcRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpc_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_response__init
                     (RpcResponse         *message)
{
  static RpcResponse init_value = RPC_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc_response__get_packed_size
                     (const RpcResponse *message)
{
  assert(message->base.descriptor == &rpc_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_response__pack
                     (const RpcResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_response__pack_to_buffer
                     (const RpcResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcResponse *
       rpc_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcResponse *)
     protobuf_c_message_unpack (&rpc_response__descriptor,
                                allocator, len, data);
}
void   rpc_response__free_unpacked
                     (RpcResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpc_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test1__init
                     (Test1         *message)
{
  static Test1 init_value = TEST1__INIT;
  *message = init_value;
}
size_t test1__get_packed_size
                     (const Test1 *message)
{
  assert(message->base.descriptor == &test1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test1__pack
                     (const Test1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test1__pack_to_buffer
                     (const Test1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test1 *
       test1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test1 *)
     protobuf_c_message_unpack (&test1__descriptor,
                                allocator, len, data);
}
void   test1__free_unpacked
                     (Test1 *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &test1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test2__init
                     (Test2         *message)
{
  static Test2 init_value = TEST2__INIT;
  *message = init_value;
}
size_t test2__get_packed_size
                     (const Test2 *message)
{
  assert(message->base.descriptor == &test2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test2__pack
                     (const Test2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test2__pack_to_buffer
                     (const Test2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test2 *
       test2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test2 *)
     protobuf_c_message_unpack (&test2__descriptor,
                                allocator, len, data);
}
void   test2__free_unpacked
                     (Test2 *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &test2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc_request__field_descriptors[3] =
{
  {
    "service",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcRequest, service),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcRequest, request),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_request__field_indices_by_name[] = {
  2,   /* field[2] = id */
  1,   /* field[1] = request */
  0,   /* field[0] = service */
};
static const ProtobufCIntRange rpc_request__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcRequest",
  "RpcRequest",
  "RpcRequest",
  "",
  sizeof(RpcRequest),
  3,
  rpc_request__field_descriptors,
  rpc_request__field_indices_by_name,
  1,  rpc_request__number_ranges,
  (ProtobufCMessageInit) rpc_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_response__field_descriptors[1] =
{
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_response__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange rpc_response__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcResponse",
  "RpcResponse",
  "RpcResponse",
  "",
  sizeof(RpcResponse),
  1,
  rpc_response__field_descriptors,
  rpc_response__field_indices_by_name,
  1,  rpc_response__number_ranges,
  (ProtobufCMessageInit) rpc_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test1__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test1, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test1__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange test1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor test1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Test1",
  "Test1",
  "Test1",
  "",
  sizeof(Test1),
  2,
  test1__field_descriptors,
  test1__field_indices_by_name,
  1,  test1__number_ranges,
  (ProtobufCMessageInit) test1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test2__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test2, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test2, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test2__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange test2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor test2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Test2",
  "Test2",
  "Test2",
  "",
  sizeof(Test2),
  2,
  test2__field_descriptors,
  test2__field_indices_by_name,
  1,  test2__number_ranges,
  (ProtobufCMessageInit) test2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc_test__method_descriptors[1] =
{
  { "GetTest", &test1__descriptor, &test2__descriptor },
};
const unsigned rpc_test__method_indices_by_name[] = {
  0         /* GetTest */
};
const ProtobufCServiceDescriptor rpc_test__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "RpcTest",
  "RpcTest",
  "RpcTest",
  "",
  1,
  rpc_test__method_descriptors,
  rpc_test__method_indices_by_name
};
void rpc_test__get_test(ProtobufCService *service,
                        const Test1 *input,
                        Test2_Closure closure,
                        void *closure_data)
{
  assert(service->descriptor == &rpc_test__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc_test__init (RpcTest_Service *service,
                     RpcTest_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc_test__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
